#ifndef QTFTPLIB_TEST_GLOBAL_H
#define QTFTPLIB_TEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTFTPLIB_TEST_LIBRARY)
#  define QTFTPLIB_TESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTFTPLIB_TESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTFTPLIB_TEST_GLOBAL_H
